'use client';

import { updateCampaignField } from '@/store/features/campaign';
import { RootState } from '@/store/store';
import React, { useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import ToolTip from './ToolTip';

type SubTab = 'EARNPOINTS' | 'REDEEMREWARDS';

const SettingsForm: React.FC = () => {
  const [activeSubTab, setActiveSubTab] = useState<SubTab>('EARNPOINTS');

  const {
    earnEnterCode,
    earnGiveStaffNumber,
    earnStaffPersonalCode,
    earnStaffScanQR,
    redeemGiveStaffNumber,
    redeemStaffPersonalCode,
    redeemStaffScanQR,
  } = useSelector((state: RootState) => state.campaing);

  const dispatch = useDispatch();

  const handleInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const { name, checked } = event.target;
    dispatch(updateCampaignField({ [name]: checked }));
  };

  const earnOptions = [
    {
      label: 'Staff members scan QR code',
      name: 'earnStaffScanQR',
      value: earnStaffScanQR,
    },
    {
      label: 'Customers enter code generated by staff',
      name: 'earnEnterCode',
      value: earnEnterCode,
    },
    {
      label: "Staff member enters personal code on customer's device",
      name: 'earnStaffPersonalCode',
      value: earnStaffPersonalCode,
    },
    {
      label: 'Customer gives customer number to staff member',
      name: 'earnGiveStaffNumber',
      value: earnGiveStaffNumber,
    },
  ];

  const redeemOptions = [
    {
      label: 'Staff members scan QR code',
      name: 'redeemStaffScanQR',
      value: redeemStaffScanQR,
    },
    {
      label: "Staff member enters personal code on customer's device",
      name: 'redeemStaffPersonalCode',
      value: redeemStaffPersonalCode,
    },

    {
      label: 'Customer gives customer number to staff member',
      name: 'redeemGiveStaffNumber',
      value: redeemGiveStaffNumber,
    },
  ];

  return (
    <div>
      {/* Sub-tabs */}
      <p className="mb-4 text-gray-600">
        Settings how customers will interact with this campaign. How they earn
        and redeem points.
      </p>
      <div className="flex text-sm border-b border-gray-200 mb-6 space-x-2">
        {(['EARNPOINTS', 'REDEEMREWARDS'] as SubTab[]).map(tab => (
          <button
            key={tab}
            className={`pb-2 px-3 font-medium transition-colors border-b-2 ${
              activeSubTab === tab
                ? 'border-blue-600 text-blue-600'
                : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
            }`}
            onClick={() => setActiveSubTab(tab)}
          >
            {tab === 'EARNPOINTS' ? 'EARN POINTS' : 'REDEEM REWARDS'}
          </button>
        ))}
      </div>

      {activeSubTab === 'EARNPOINTS' && (
        <div className="bg-gray-50 p-4 rounded-md border border-gray-200">
           <div className="flex items-center gap-2 mb-3">
               <h3 className="font-medium text-gray-900">How can customers earn points?</h3>
               <ToolTip content="Select the methods customers can use to earn points." />
           </div>
          <div className="space-y-3">
            {earnOptions.map((option, index) => {
                const { label, name, value } = option;
                return (
                <label key={index} className="flex items-center cursor-pointer">
                    <input
                    type="checkbox"
                    id={`earn-${index}`}
                    className="mr-3 w-4 h-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500"
                    name={name}
                    checked={value}
                    onChange={handleInputChange}
                    />
                    <span className="text-gray-700">{label}</span>
                </label>
                );
            })}
          </div>
        </div>
      )}

      {activeSubTab === 'REDEEMREWARDS' && (
        <div className="bg-gray-50 p-4 rounded-md border border-gray-200">
           <div className="flex items-center gap-2 mb-3">
               <h3 className="font-medium text-gray-900">How can customers redeem rewards?</h3>
               <ToolTip content="Select the methods customers can use to redeem earned points." />
           </div>
          <div className="space-y-3">
            {redeemOptions.map((option, index) => {
                const { label, name, value } = option;
                return (
                 <label key={index} className="flex items-center cursor-pointer">
                    <input
                    type="checkbox"
                    id={`redeem-${index}`}
                    className="mr-3 w-4 h-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500"
                    name={name}
                    checked={value}
                    onChange={handleInputChange}
                    />
                    <span className="text-gray-700">{label}</span>
                </label>
                );
            })}
          </div>
        </div>
      )}
    </div>
  );
};

export default SettingsForm;
