import { MigrationInterface, QueryRunner } from "typeorm";

export class FixMissingRewardsColumns1769508751661 implements MigrationInterface {
    name = 'FixMissingRewardsColumns1769508751661'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "Rewards" ADD "type" character varying NOT NULL DEFAULT 'STANDARD'`);
        await queryRunner.query(`ALTER TABLE "Rewards" ADD "config" json`);
        await queryRunner.query(`ALTER TABLE "Rewards" ADD "quantityAvailable" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "Rewards" ADD "quantityRemaining" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "Code Generated By Staffs" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "CustomersRewards" ADD "uniqueCode" character varying`);
        await queryRunner.query(`ALTER TYPE "public"."voucher_type_enum" RENAME TO "voucher_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."voucher_type_enum" AS ENUM('LINK', 'CREDENTIALS', 'MCOM_LOYALTY_TIER', 'MCOM_MALL_TIER', 'MALL_OFFER')`);
        await queryRunner.query(`ALTER TABLE "voucher" ALTER COLUMN "type" TYPE "public"."voucher_type_enum" USING "type"::"text"::"public"."voucher_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."voucher_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "Code Generated By Staffs" ADD CONSTRAINT "FK_886d6598469c3f8efc4da94bc58" FOREIGN KEY ("userId") REFERENCES "Users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "Code Generated By Staffs" DROP CONSTRAINT "FK_886d6598469c3f8efc4da94bc58"`);
        await queryRunner.query(`CREATE TYPE "public"."voucher_type_enum_old" AS ENUM('LINK', 'CREDENTIALS', 'MCOM_LOYALTY_TIER', 'MCOM_MALL_TIER', 'MCOM_BUNDLE', 'MALL_OFFER')`);
        await queryRunner.query(`ALTER TABLE "voucher" ALTER COLUMN "type" TYPE "public"."voucher_type_enum_old" USING "type"::"text"::"public"."voucher_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."voucher_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."voucher_type_enum_old" RENAME TO "voucher_type_enum"`);
        await queryRunner.query(`ALTER TABLE "CustomersRewards" DROP COLUMN "uniqueCode"`);
        await queryRunner.query(`ALTER TABLE "Code Generated By Staffs" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "Rewards" DROP COLUMN "quantityRemaining"`);
        await queryRunner.query(`ALTER TABLE "Rewards" DROP COLUMN "quantityAvailable"`);
        await queryRunner.query(`ALTER TABLE "Rewards" DROP COLUMN "config"`);
        await queryRunner.query(`ALTER TABLE "Rewards" DROP COLUMN "type"`);
    }

}
