import { MigrationInterface, QueryRunner } from "typeorm";

export class AddTypeAndConfigToRewards1769502574240 implements MigrationInterface {
    name = 'AddTypeAndConfigToRewards1769502574240'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "Rewards" ADD "type" character varying NOT NULL DEFAULT 'STANDARD'`);
        await queryRunner.query(`ALTER TABLE "Rewards" ADD "config" json`);
        await queryRunner.query(`ALTER TABLE "Rewards" ADD "quantityAvailable" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "Rewards" ADD "quantityRemaining" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "Code Generated By Staffs" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "Code Generated By Staffs" ADD CONSTRAINT "FK_886d6598469c3f8efc4da94bc58" FOREIGN KEY ("userId") REFERENCES "Users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "Code Generated By Staffs" DROP CONSTRAINT "FK_886d6598469c3f8efc4da94bc58"`);
        await queryRunner.query(`ALTER TABLE "Code Generated By Staffs" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "Rewards" DROP COLUMN "quantityRemaining"`);
        await queryRunner.query(`ALTER TABLE "Rewards" DROP COLUMN "quantityAvailable"`);
        await queryRunner.query(`ALTER TABLE "Rewards" DROP COLUMN "config"`);
        await queryRunner.query(`ALTER TABLE "Rewards" DROP COLUMN "type"`);
    }

}
