import { Campaign } from '../../../modules/campaign/entities/campaign.entity';
import { AbstractBaseEntity } from '../../../entities/base.entity';
import { Column, Entity, JoinColumn, ManyToOne } from 'typeorm';
import { Staff } from '../../../modules/staff/entities/staff.entity';
import { User } from '../../user/entities/user.entity';

@Entity('Code Generated By Staffs')
export class CodeGeneratedByStaffs extends AbstractBaseEntity {
  @ManyToOne(() => Campaign, (campaign) => campaign.id, { onDelete: 'CASCADE' })
  @JoinColumn()
  campaign: Campaign;

  @ManyToOne(() => Staff, (staff) => staff.id, { nullable: true })
  @JoinColumn()
  staff: Staff;

  @ManyToOne(() => User, (user) => user.id, { nullable: true })
  @JoinColumn()
  user: User;

  @Column({ type: 'timestamp' })
  expiry: Date;

  @Column()
  points: number;

  @Column({ nullable: false })
  code: string;

  @Column({ nullable: false, default: '1' })
  type: string;
}
