import { Checkbox } from '@/components/ui/checkbox';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import React from 'react';

const SettingsSubMenu = () => {
  const subTabMenu = ['earn points', 'redeem points'];

  const earnOptions = [
    'Staff member scans QR code',
    'Customer enters code generated by staff member',
    "Staff member enters personal code on customer's device",
    'Customer gives customer number to staff member',
  ];

  const redeemOptions = [
    'Staff member scans QR code',
    "Staff member enters personal code on customer's device",
    'Customer gives customer number to staff member',
  ];

  return (
    <Tabs defaultValue={subTabMenu[0]}>
      <TabsList>
        {subTabMenu.map((menu, i) => (
          <TabsTrigger value={menu} key={i}>
            <p className="text-black font-normal">{menu.toUpperCase()}</p>
          </TabsTrigger>
        ))}
      </TabsList>
      <TabsContent value="earn points">
        <div className="bg-[#f5f5f5] p-2 rounded-sm shadow-md">
          How can customers claim points? A QR code is convenient if staff
          members have a mobile device to scan the code. It is also possible to
          have a staff member generate a code that the customer can enter
          himself, or to have the customer hand over the phone so a staff member
          can enter a code. Finally, it is possible for the customer to give
          their customer number to which the points can be credited.
        </div>
        <div className="flex flex-col justify-start mt-5 gap-3">
          {earnOptions.map((option, i) => (
            <span className="flex gap-2 items-center text-lg" key={i}>
              <Checkbox />
              <p>{option}</p>
            </span>
          ))}
        </div>
      </TabsContent>
      <TabsContent value="redeem points">
        <div>
          <h3 className="font-medium text-lg">
            How can customers redeem rewards?
          </h3>

          <div className="flex flex-col justify-start mt-5 gap-3">
            {redeemOptions.map((option, i) => (
              <span className="flex gap-2 items-center text-lg" key={i}>
                <Checkbox />
                <p>{option}</p>
              </span>
            ))}
          </div>
        </div>
      </TabsContent>
    </Tabs>
  );
};

const SettingsMenu = () => {
  return (
    <div className="w-full ">
      <div className="flex flex-col space-y-6 mt-4">
        <SettingsSubMenu />
      </div>
    </div>
  );
};

export default SettingsMenu;
